def build(bld):
    prog = bld.new_task_gen( 'cxx', 'program' )
    prog.source = bld.glob("*.cpp")
    prog.includes = '../include'
    prog.target = 'GenerateMapServer'
    prog.install_path = None
    prog.uselib_local = 'MapGen ServersShared ServersSharedGfx \
    ServersSharedItems ServersSharedNet ServersSharedXML \
ServersSharedDatabase Shared SharedNet'
    prog.defines = 'USE_SSL USE_XML'
    prog.uselib='SHARED SERVERSSHARED MAPGEN'
