def build(bld):
    staticlib = bld.new_task_gen( 'cxx', 'staticlib' )
    staticlib.source = bld.glob("*.cpp")
    staticlib.includes = '../include ../../include ../../../../Shared/include ../../Common/include'
    staticlib.target = 'ServersSharedNet'
    staticlib.install_path = None
    staticlib.defines = 'USE_SSL'
    staticlib.export_incdirs='../include'
    staticlib.uselib_local='SharedFileSystem SharedNet'

