def configure(conf):
    return

def build(bld):
    staticlib = bld.new_task_gen( 'cxx', 'staticlib' )
    staticlib.source = bld.glob("*.cpp")
    staticlib.includes = '../include'
    staticlib.target = 'SharedUtility'
    staticlib.install_path = None
    staticlib.export_incdirs='../include'
