def build(bld):
    prog = bld.new_task_gen( 'cxx', 'program' )
    prog.source = bld.glob("*.cpp")
    prog.includes = '../include'
    prog.target = 'QualTool'
    prog.install_path = None
    prog.uselib_local = 'MapGen ServersShared ServersSharedNet \
    ServersSharedDrawing ServersSharedGfx ServersSharedXML \
ServersSharedCommon ServersSharedItems ServersSharedDatabase Shared'
    prog.defines = 'USE_SSL'
    prog.uselib='SHARED SERVERSSHARED MAPGEN'
