from waftools import mc2test

def unit_test(bld, target, source ):
   test = mc2test.unit_test(bld, target, source,
                            'ServersServers ServersShared ServersSharedNet \
                            ServersSharedXML ServersSharedCommon SharedNet \
                            Shared SharedUtility',
                            'SHARED SERVER SERVERSSHARED OPENSSL XERCES')
   test.defines = 'USE_SSL USE_XML'
   return test


def build(bld):
   unit_test(bld, 'ServerRegionIDsTest', 'ServerRegionIDsTest.cpp' )
   unit_test(bld, 'UserImageTest', 'UserImageTest.cpp' )
   unit_test(bld, 'CategoryTreeRegionConfigurationTest', 'CategoryTreeRegionConfigurationTest.cpp' )
   unit_test(bld, 'ClientSettingTest', 'ClientSettingTest.cpp' )

