def build(bld):
    prog = bld.new_task_gen( 'cxx', 'program' )
    prog.source = bld.glob('*.cpp')
    prog.includes = '../include'
    prog.target = 'TCPProxy'
    prog.install_path = None
    prog.uselib_local = 'ServersShared ServersSharedNet Shared SharedNet'
    prog.uselib = 'SHARED SERVERSSHARED TECLA'
