from waftools import mc2test

def unit_test(bld, target, source):
   return mc2test.unit_test(bld, target, source,
                            'ServersSharedDrawing Shared',
                            'SHARED')

def create_unit_tests(bld):
   # create a unit test for each .cpp file
   for source in bld.glob('*.cpp'):
      unit_test(bld, source[:-4], source)

def build(bld):
   create_unit_tests(bld)

