from waftools import mc2test
def unit_test(bld, target, source):
   # setup sources
   sources = [ source ]
   sources.extend(mc2test.create_sources(bld, '../src/', '*.cpp',
                                          'ExtServiceModule.cpp'))

   test = mc2test.unit_test(bld, target, sources,
                             'Module ServersShared ServersSharedNet \
    ServersSharedDrawing ServersSharedGfx ServersSharedXML \
ServersSharedCommon ServersSharedItems ServersSharedDatabase ServersSharedJSON \
SharedNet \
Shared',
                             'MODULE SHARED SERVERSSHARED' )
   test.defines = 'USE_XML'

   return test

def build(bld):
   unit_test(bld, 'MaxCountTest', 'MaxCountTest.cpp' )
   unit_test(bld, 'QypeTest', 'QypeTest.cpp' )
