def build(bld):
    staticlib = bld.new_task_gen( 'cxx', 'staticlib' )
    staticlib.source = bld.glob("*.cpp")
    staticlib.includes = '../include \
../../../../Shared/include'
    staticlib.target = 'ServersSharedCommon'
    staticlib.uselib_local='SharedUtility'
    staticlib.install_path = None
    staticlib.export_incdirs='../include'

