/*
Copyright (c) 1999 - 2010, Vodafone Group Services Ltd
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of the Vodafone Group Services Ltd nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "TrafficDataTypes.h"

struct PhraseStruct {
   TrafficDataTypes::phrase m_value;
   const char* m_text;
};

struct PhraseStruct phraseArray[] = {
   { TrafficDataTypes::ABL, "Abnormal load(s)" },
   { TrafficDataTypes::ABX, "Exceptional load warning cleared" },
   { TrafficDataTypes::ACA, "Earlier accident(s)" },
   { TrafficDataTypes::ACB, "Accident involving bus(es)" },
   { TrafficDataTypes::ACD, "Secondary accident(s)" },
   { TrafficDataTypes::ACE, "Chemical spillage accident(s)" },
   { TrafficDataTypes::ACF, "Fuel spillage accident(s)" },
   { TrafficDataTypes::ACH, "Accident involving heavy lorr(y/ies)" },
   { TrafficDataTypes::ACI, "Accident(s)" },
   { TrafficDataTypes::ACL, "Accident clearance" },
   { TrafficDataTypes::ACM, "Multi-vehicle accident" },
   { TrafficDataTypes::ACS, "Serious accident(s)" },
   { TrafficDataTypes::ACW, "Accident investigation work" },
   { TrafficDataTypes::ACX, "Accident cleared" },
   { TrafficDataTypes::ACZ, "Accident(s) involving hazardous materials" },
   { TrafficDataTypes::AIC, "Air crash" },
   { TrafficDataTypes::AIR, "Air raid" },
   { TrafficDataTypes::AJA, "Jack-knifed articulated lorr(y/ies)" },
   { TrafficDataTypes::AJC, "Jack-knifed caravan(s)" },
   { TrafficDataTypes::AJT, "Jack-knifed trailer(s)" },
   { TrafficDataTypes::ALA, "Alarm call: important new information on this frequency follows now" },
   { TrafficDataTypes::ALC, "Alarm call: important new information will be broadcast between these times" },
   { TrafficDataTypes::ALL, "All accidents cleared" },
   { TrafficDataTypes::ALR, "Additional local information is provided by another TMC service" },
   { TrafficDataTypes::ANH, "Herd of animals on the road" },
   { TrafficDataTypes::ANL, "Large animals on the road" },
   { TrafficDataTypes::ANM, "Animals on the road" },
   { TrafficDataTypes::AOI, "Oil spillage accident(s)" },
   { TrafficDataTypes::AOL, "Overturned heavy lorr(y/ies)" },
   { TrafficDataTypes::AOV, "Overturned vehicle(s)" },
   { TrafficDataTypes::APF, "All carparks full" },
   { TrafficDataTypes::APT, "Additional public transport information is provided by another TMC service" },
   { TrafficDataTypes::AQD, "Danger of aquaplaning" },
   { TrafficDataTypes::ASP, "Vehicle(s) spun around" },
   { TrafficDataTypes::ATR, "Additional regional information is provided by another TMC service" },
   { TrafficDataTypes::AVL, "Avalanches" },
   { TrafficDataTypes::AVS, "Average speed" },
   { TrafficDataTypes::BCL, "Broken-down vehicle clearance" },
   { TrafficDataTypes::BDB, "Broken down bus(es)" },
   { TrafficDataTypes::BDX, "Breakdown cleared" },
   { TrafficDataTypes::BKD, "Broken down vehicle(s)" },
   { TrafficDataTypes::BLI, "Blizzard" },
   { TrafficDataTypes::BLO, "Blowing dust" },
   { TrafficDataTypes::BLS, "Blowing snow" },
   { TrafficDataTypes::BRB, "Bridge blocked" },
   { TrafficDataTypes::BRC, "Bridge closed" },
   { TrafficDataTypes::BRP, "Burst pipe" },
   { TrafficDataTypes::BSI, "Bus services irregular. Delays" },
   { TrafficDataTypes::BUN, "Bus services not operating" },
   { TrafficDataTypes::BWM, "Burst water main" },
   { TrafficDataTypes::CAA, "Carpool lane in operation" },
   { TrafficDataTypes::CAC, "Cancellations" },
   { TrafficDataTypes::CAL, "Message cancelled" },
   { TrafficDataTypes::CBW, "Closures due to bad weather" },
   { TrafficDataTypes::CCB, "Connecting carriageway blocked" },
   { TrafficDataTypes::CCC, "Connecting carriageway closed" },
   { TrafficDataTypes::CHI, "Children on roadway" },
   { TrafficDataTypes::CLE, "Clearing action" },
   { TrafficDataTypes::CLW, "Clearance work" },
   { TrafficDataTypes::CON, "Overnight closures" },
   { TrafficDataTypes::COO, "Emergancy telephones not working" },
   { TrafficDataTypes::COW, "Convoy service due to bad weather" },
   { TrafficDataTypes::CPW, "Roads permanently closed for the winter" },
   { TrafficDataTypes::CRC, "Carpool restrictions changed" },
   { TrafficDataTypes::CRX, "Carpool restrictions lifted" },
   { TrafficDataTypes::CTR, "Contraflow" },
   { TrafficDataTypes::CTT, "Concentration" },
   { TrafficDataTypes::CTX, "Contraflow removed" },
   { TrafficDataTypes::CV1, "Closed for vehicles with only one occupant" },
   { TrafficDataTypes::CV3, "Closed for vehicles with less than three occupants" },
   { TrafficDataTypes::CVX, "Convoy cleared" },
   { TrafficDataTypes::CVY, "Convoy(s)" },
   { TrafficDataTypes::CWC, "All carriageways cleared" },
   { TrafficDataTypes::CYC, "Cyclists on roadway" },
   { TrafficDataTypes::DCD, "Difficult driving conditions" },
   { TrafficDataTypes::DCE, "Extremely hazardous driving conditions" },
   { TrafficDataTypes::DCL, "Air raid warning cancelled" },
   { TrafficDataTypes::DCN, "Driving conditions improved" },
   { TrafficDataTypes::DCZ, "Hazardous driving conditions" },
   { TrafficDataTypes::DEI, "Detailed information will be given on audio program broadcast" },
   { TrafficDataTypes::DEU, "Delayed until further notice" },
   { TrafficDataTypes::DEX, "Delays cleared" },
   { TrafficDataTypes::DIP, "Detailed information is provided by another TMC provider" },
   { TrafficDataTypes::DLL, "Long delays" },
   { TrafficDataTypes::DLY, "Delays" },
   { TrafficDataTypes::DO, "Diversion in operation" },
   { TrafficDataTypes::DPN, "Service suspended" },
   { TrafficDataTypes::DUD, "Delays of uncertain duration" },
   { TrafficDataTypes::DVL, "Very long delays" },
   { TrafficDataTypes::DXX, "Delays expected to be cleared" },
   { TrafficDataTypes::EAM, "Athletics meeting" },
   { TrafficDataTypes::EBA, "Bomb alert" },
   { TrafficDataTypes::EBF, "Bull fight" },
   { TrafficDataTypes::EBG, "Ball game" },
   { TrafficDataTypes::EBT, "Boxing tournament" },
   { TrafficDataTypes::ECL, "Give way to emergency vehicles on the carpool lane" },
   { TrafficDataTypes::ECM, "Cricket match" },
   { TrafficDataTypes::ECR, "Crowd" },
   { TrafficDataTypes::ECY, "Cycle race" },
   { TrafficDataTypes::EFA, "Fair" },
   { TrafficDataTypes::EFM, "Football match" },
   { TrafficDataTypes::EFR, "Emergancy call facilities restored" },
   { TrafficDataTypes::EGT, "Golf tournament" },
   { TrafficDataTypes::EHL, "Give way to emergency vehicles on the heavy vehicle lane" },
   { TrafficDataTypes::EIS, "International sports meeting" },
   { TrafficDataTypes::EMH, "High-speed emergency vehicle(s)" },
   { TrafficDataTypes::EMR, "March" },
   { TrafficDataTypes::EMT, "Match" },
   { TrafficDataTypes::EMV, "Emergency vehicle(s)" },
   { TrafficDataTypes::EMX, "Emergency vehicle warning cleared" },
   { TrafficDataTypes::EPD, "Public disturbance" },
   { TrafficDataTypes::EPR, "Procession" },
   { TrafficDataTypes::EQD, "Earthquake damage" },
   { TrafficDataTypes::ERA, "Race meeting" },
   { TrafficDataTypes::ESA, "Security alert" },
   { TrafficDataTypes::ESH, "Show" },
   { TrafficDataTypes::ESI, "Securitu incident" },
   { TrafficDataTypes::ESJ, "Show jumping" },
   { TrafficDataTypes::ESM, "Several major events" },
   { TrafficDataTypes::ESO, "State occasion" },
   { TrafficDataTypes::ESP, "Sports meeting" },
   { TrafficDataTypes::ESS, "Sightseers obstruction access" },
   { TrafficDataTypes::EST, "Strike" },
   { TrafficDataTypes::ESX, "Sports traffic cleared" },
   { TrafficDataTypes::ESY, "Security alert cleared" },
   { TrafficDataTypes::ETN, "Traffic has returned to normal" },
   { TrafficDataTypes::ETO, "Tournament" },
   { TrafficDataTypes::ETT, "Tennis tournament" },
   { TrafficDataTypes::EVA, "Evacuation" },
   { TrafficDataTypes::EVC, "Ceremonial event" },
   { TrafficDataTypes::EVD, "Demonstration" },
   { TrafficDataTypes::EVF, "Festival" },
   { TrafficDataTypes::EVM, "Major event" },
   { TrafficDataTypes::EVP, "Parade" },
   { TrafficDataTypes::EVX, "Exhibition" },
   { TrafficDataTypes::EWS, "Water sports meeting" },
   { TrafficDataTypes::EWT, "Winter sports meeting" },
   { TrafficDataTypes::EXB, "Express lanes blocked" },
   { TrafficDataTypes::EXC, "Express lanes closed" },
   { TrafficDataTypes::EXS, "Severe exhaust pollution" },
   { TrafficDataTypes::FFX, "Fog forecast withdrawn" },
   { TrafficDataTypes::FIG, "Grass fire" },
   { TrafficDataTypes::FIR, "Serious fire" },
   { TrafficDataTypes::FLD, "Flooding" },
   { TrafficDataTypes::FLF, "Flash floods" },
   { TrafficDataTypes::FLO, "Flow" },
   { TrafficDataTypes::FLT, "Fallen trees" },
   { TrafficDataTypes::FOD, "Dense fog" },
   { TrafficDataTypes::FOF, "Freezing fog" },
   { TrafficDataTypes::FOG, "Fog" },
   { TrafficDataTypes::FOP, "Patchy fog" },
   { TrafficDataTypes::FOX, "Fog cleared" },
   { TrafficDataTypes::FPC, "Fallen power cables" },
   { TrafficDataTypes::FRH, "Heavy frost" },
   { TrafficDataTypes::FRO, "Frost" },
   { TrafficDataTypes::FSN, "Ferry service not operating" },
   { TrafficDataTypes::FUE, "Oil on road" },
   { TrafficDataTypes::FUN, "Funfair" },
   { TrafficDataTypes::GAL, "Gales" },
   { TrafficDataTypes::GAS, "Gas leak" },
   { TrafficDataTypes::GMW, "Gas main work" },
   { TrafficDataTypes::GP, "Gritting vehicle in use" },
   { TrafficDataTypes::GUN, "Gunfire on roadway" },
   { TrafficDataTypes::HAD, "Damaging hail" },
   { TrafficDataTypes::HAI, "Hail" },
   { TrafficDataTypes::HAX, "Hazardous load warning cleared" },
   { TrafficDataTypes::HAZ, "Vehicle(s) carrying hazardous materials" },
   { TrafficDataTypes::HBD, "Broken down heavy lorr(y/ies)" },
   { TrafficDataTypes::HLL, "Temporary height limit lifted" },
   { TrafficDataTypes::HLT, "Temporary height limit" },
   { TrafficDataTypes::HSC, "High-speed chase" },
   { TrafficDataTypes::HUR, "Hurricane force winds" },
   { TrafficDataTypes::IAV, "Information available" },
   { TrafficDataTypes::IBU, "Ice build-up" },
   { TrafficDataTypes::ICP, "Icy patches" },
   { TrafficDataTypes::IMA, "Almost impassable" },
   { TrafficDataTypes::IMP, "Impassable" },
   { TrafficDataTypes::INS, "Incident(s)" },
   { TrafficDataTypes::IVD, "Individual vehicle data" },
   { TrafficDataTypes::LAP, "Carpool lane closed" },
   { TrafficDataTypes::LB1, "One lane blocked" },
   { TrafficDataTypes::LB2, "Two lanes blocked" },
   { TrafficDataTypes::LB3, "Three lanes blocked" },
   { TrafficDataTypes::LBA, "Crawler lane blocked" },
   { TrafficDataTypes::LBB, "Bus lane blocked" },
   { TrafficDataTypes::LBC, "Centre lane(s) blocked" },
   { TrafficDataTypes::LBD, "Slow vehicle lane blocked" },
   { TrafficDataTypes::LBE, "Emergency lane blocked" },
   { TrafficDataTypes::LBH, "Hard shoulder blocked" },
   { TrafficDataTypes::LBK, "Lane(s) blocked" },
   { TrafficDataTypes::LBL, "Left lane(s) blocked" },
   { TrafficDataTypes::LBP, "Carpool lane blocked" },
   { TrafficDataTypes::LBR, "Right lane(s) blocked" },
   { TrafficDataTypes::LBT, "Turning lane blocked" },
   { TrafficDataTypes::LBV, "Heavy vehicle lane blocked" },
   { TrafficDataTypes::LBX, "Lane blockages cleared" },
   { TrafficDataTypes::LC1, "One lane closed" },
   { TrafficDataTypes::LC2, "Two lanes closed" },
   { TrafficDataTypes::LC3, "Three lanes closed" },
   { TrafficDataTypes::LCA, "Crawler lane closed" },
   { TrafficDataTypes::LCB, "Bus lane closed" },
   { TrafficDataTypes::LCC, "Centre lane(s) closed" },
   { TrafficDataTypes::LCD, "Slow vehicle lane closed" },
   { TrafficDataTypes::LCE, "Emergency lane closed" },
   { TrafficDataTypes::LCF, "Level crossing failure" },
   { TrafficDataTypes::LCH, "Hard shoulder closed" },
   { TrafficDataTypes::LCI, "Loose chippings" },
   { TrafficDataTypes::LCL, "Left lane(s) closed" },
   { TrafficDataTypes::LCP, "Overtaking lane(s) closed" },
   { TrafficDataTypes::LCR, "Right lane(s) closed" },
   { TrafficDataTypes::LCS, "Lane(s) closed" },
   { TrafficDataTypes::LCT, "Turning lane closed" },
   { TrafficDataTypes::LCV, "Heavy vehicle lane closed" },
   { TrafficDataTypes::LCW, "Level crossing now working normally" },
   { TrafficDataTypes::LLB, "Local lanes blocked" },
   { TrafficDataTypes::LLC, "Local lanes closed" },
   { TrafficDataTypes::LLD, "Long load(s)" },
   { TrafficDataTypes::LLL, "Temporary length limit lifted" },
   { TrafficDataTypes::LLT, "Temporary length limit" },
   { TrafficDataTypes::LO1, "Carriageway reduced to one lane" },
   { TrafficDataTypes::LO2, "Carriageway reduced to two lanes" },
   { TrafficDataTypes::LO3, "Carriageway reduced to three lanes" },
   { TrafficDataTypes::LPB, "Left-hand parallel carriageway blocked" },
   { TrafficDataTypes::LPC, "Left-hand parallel carriageway closed" },
   { TrafficDataTypes::LPX, "No problems to report" },
   { TrafficDataTypes::LRR, "Normal lane regulations restored" },
   { TrafficDataTypes::LRS, "Lane closures removed" },
   { TrafficDataTypes::LRX, "Lane restrictions lifted" },
   { TrafficDataTypes::LS1, "Stationary traffic" },
   { TrafficDataTypes::LS2, "Queuing traffic" },
   { TrafficDataTypes::LS3, "Slow traffic" },
   { TrafficDataTypes::LS4, "Heavy traffic" },
   { TrafficDataTypes::LS5, "Traffic flowing freely" },
   { TrafficDataTypes::LS6, "Long queues" },
   { TrafficDataTypes::LSG, "Low sun glare" },
   { TrafficDataTypes::LSL, "Landslips" },
   { TrafficDataTypes::LSO, "Traffic problem" },
   { TrafficDataTypes::LSR, "Loose sand on road" },
   { TrafficDataTypes::LTH, "Traffic heavier than normal" },
   { TrafficDataTypes::LTM, "Traffic very much heavier than normal" },
   { TrafficDataTypes::LVB, "Overtaking lane(s) blocked" },
   { TrafficDataTypes::MAR, "Marathon" },
   { TrafficDataTypes::MHR, "Moving hazards on the road" },
   { TrafficDataTypes::MIL, "Military convoy(s)" },
   { TrafficDataTypes::MKT, "Market" },
   { TrafficDataTypes::MSR, "Electronic signs repaired" },
   { TrafficDataTypes::MUD, "Mud slide" },
   { TrafficDataTypes::MVL, "Motor vehicle restrictions lifted" },
   { TrafficDataTypes::NAR, "Next arrival" },
   { TrafficDataTypes::NCR, "Normal services resumed" },
   { TrafficDataTypes::NDT, "Next departure" },
   { TrafficDataTypes::NIA, "No information available" },
   { TrafficDataTypes::NLS, "Narrow lanes" },
   { TrafficDataTypes::NML, "Null message - completely silent" },
   { TrafficDataTypes::NOO, "Emergency telephone number not working" },
   { TrafficDataTypes::NRL, "New road layout" },
   { TrafficDataTypes::NUL, "Null message with location" },
   { TrafficDataTypes::OBR, "X object(s) on roadway" },
   { TrafficDataTypes::OCC, "Occupancy" },
   { TrafficDataTypes::OCL, "Obstacle clearance" },
   { TrafficDataTypes::OHV, "Overheight vehicle(s)" },
   { TrafficDataTypes::OHW, "Overheight warning system triggered" },
   { TrafficDataTypes::OHX, "Obstruction(s) on the road" },
   { TrafficDataTypes::OIL, "Petrol on roadway" },
   { TrafficDataTypes::OMV, "Objects falling from moving vehicle" },
   { TrafficDataTypes::OPE, "Open" },
   { TrafficDataTypes::OSI, "Obstacle signalling" },
   { TrafficDataTypes::OWW, "Obstruction warning withdrawn" },
   { TrafficDataTypes::PAC, "Passable with care" },
   { TrafficDataTypes::PCB, "Parallel carriageway blocked" },
   { TrafficDataTypes::PCC, "Parallel carriageway closed" },
   { TrafficDataTypes::PEO, "People on roadway" },
   { TrafficDataTypes::PFN, "No parking allowed" },
   { TrafficDataTypes::PFS, "Only a few spaces available" },
   { TrafficDataTypes::PIX, "No parking information available" },
   { TrafficDataTypes::PKO, "Car park full" },
   { TrafficDataTypes::PKT, "Park and ride trip time" },
   { TrafficDataTypes::PMN, "No more parking spaces available" },
   { TrafficDataTypes::PMS, "Multi story car parks full" },
   { TrafficDataTypes::PRA, "Precipitation on the area" },
   { TrafficDataTypes::PRC, "No park and ride information to report" },
   { TrafficDataTypes::PRI, "Park and ride information available again" },
   { TrafficDataTypes::PRL, "Normal parking restrictions lifted" },
   { TrafficDataTypes::PRN, "Park and ride service not operating" },
   { TrafficDataTypes::PRO, "Park and ride service operating" },
   { TrafficDataTypes::PRS, "Special public transport services operating" },
   { TrafficDataTypes::PRV, "Prohibited vehicle(s) on the roadway" },
   { TrafficDataTypes::PRX, "No park and ride information" },
   { TrafficDataTypes::PSA, "X parking spaces available enough spaces available" },
   { TrafficDataTypes::PSL, "Special parking restrictions lifted" },
   { TrafficDataTypes::PSN, "Less than X parking spaces available" },
   { TrafficDataTypes::PSR, "Special parking restrictions in force" },
   { TrafficDataTypes::PSS, "Passable" },
   { TrafficDataTypes::PTB, "Police directing traffic via the bus lane" },
   { TrafficDataTypes::PTC, "Police directing traffic via the carpool lane" },
   { TrafficDataTypes::PTH, "Police directing traffic via the heavy vehicle lane" },
   { TrafficDataTypes::PTN, "Public transport services not operating" },
   { TrafficDataTypes::PTS, "Public transport strike" },
   { TrafficDataTypes::RAC, "Rail crash" },
   { TrafficDataTypes::RAD, "Rerouting adviced" },
   { TrafficDataTypes::RAF, "Freezing rain" },
   { TrafficDataTypes::RAH, "Heavy rain" },
   { TrafficDataTypes::RAI, "Rain" },
   { TrafficDataTypes::RBA, "Blocked ahead" },
   { TrafficDataTypes::RBD, "Bridge demolition work" },
   { TrafficDataTypes::RBE, "Entry blocked" },
   { TrafficDataTypes::RBI, "Black ice" },
   { TrafficDataTypes::RBL, "Blasting work" },
   { TrafficDataTypes::RBM, "Bridge maintenance work" },
   { TrafficDataTypes::RBX, "Exit blocked" },
   { TrafficDataTypes::RC2, "Road cleared" },
   { TrafficDataTypes::RCA, "Closed ahead" },
   { TrafficDataTypes::RCB, "Blocked" },
   { TrafficDataTypes::RCD, "Closed" },
   { TrafficDataTypes::RCE, "Entry slip road(s) closed" },
   { TrafficDataTypes::RCI, "Ramp control signals working incorrectly" },
   { TrafficDataTypes::RCL, "Road free again" },
   { TrafficDataTypes::RCP, "Right-hand parallel carriageway closed" },
   { TrafficDataTypes::RCR, "Reopened" },
   { TrafficDataTypes::RCT, "No through traffic" },
   { TrafficDataTypes::RCW, "Construction work" },
   { TrafficDataTypes::RCX, "Road conditions improved" },
   { TrafficDataTypes::RDW, "Reckless driver(s)" },
   { TrafficDataTypes::REB, "Entry slip road blocked" },
   { TrafficDataTypes::REC, "Entry slip road closed" },
   { TrafficDataTypes::REL, "Restrictions lifted" },
   { TrafficDataTypes::REO, "Entry reopened" },
   { TrafficDataTypes::RET, "Restrictions" },
   { TrafficDataTypes::REW, "Rescue and recovery work" },
   { TrafficDataTypes::REX, "Slip roads closed" },
   { TrafficDataTypes::RIC, "Ice" },
   { TrafficDataTypes::RIN, "Road closed intermittently" },
   { TrafficDataTypes::RIS, "Tram service not operating" },
   { TrafficDataTypes::RLS, "Leaves on road" },
   { TrafficDataTypes::RLU, "Road layout unchanged" },
   { TrafficDataTypes::RMD, "Mud on road" },
   { TrafficDataTypes::RMK, "Maintenance work" },
   { TrafficDataTypes::RMM, "Maintenance vehicles merging into traffic flow" },
   { TrafficDataTypes::RMP, "No motor vehicles" },
   { TrafficDataTypes::RMV, "Slow moving maintenance vehicle(s)" },
   { TrafficDataTypes::RMW, "Road marking work" },
   { TrafficDataTypes::RMX, "Maintenance work cleared, slow moving maintenance vehicle warnings withdrawn" },
   { TrafficDataTypes::RNL, "New roadworks layout" },
   { TrafficDataTypes::RNW, "Ramp control signals not working" },
   { TrafficDataTypes::ROA, "All carriageways reopened" },
   { TrafficDataTypes::ROC, "Rockfalls" },
   { TrafficDataTypes::RPB, "Right-hand parallel carriageway blocked" },
   { TrafficDataTypes::RPC, "Road surface in poor condition" },
   { TrafficDataTypes::RRI, "Intermittent rerouting" },
   { TrafficDataTypes::RRU, "Rugby match" },
   { TrafficDataTypes::RRW, "Central reservation work" },
   { TrafficDataTypes::RSB, "Slip roads blocked" },
   { TrafficDataTypes::RSI, "Rail services irregular, delays" },
   { TrafficDataTypes::RSL, "Slippery road" },
   { TrafficDataTypes::RSN, "Rail services not operating" },
   { TrafficDataTypes::RSO, "Slip roads reopened" },
   { TrafficDataTypes::RSR, "Slip road restrictions" },
   { TrafficDataTypes::RTO, "Public transport services resumed" },
   { TrafficDataTypes::RWC, "Roadworks cleared" },
   { TrafficDataTypes::RWI, "Wet and icy roads" },
   { TrafficDataTypes::RWK, "Roadworks" },
   { TrafficDataTypes::RWL, "Long-term roadworks" },
   { TrafficDataTypes::RWM, "Major roadworks" },
   { TrafficDataTypes::RWR, "Resurfacing work" },
   { TrafficDataTypes::RWX, "Roadwork clearance in progress" },
   { TrafficDataTypes::RXB, "Exit slip road blocked" },
   { TrafficDataTypes::RXC, "Exit slip road closed" },
   { TrafficDataTypes::RXD, "Exit slip road(s) closed" },
   { TrafficDataTypes::RXO, "Exit reopened" },
   { TrafficDataTypes::SAB, "Service area busy" },
   { TrafficDataTypes::SAL, "Salting in progress" },
   { TrafficDataTypes::SAN, "Sandstorms" },
   { TrafficDataTypes::SAO, "Service area overcrowded, drive to another service area" },
   { TrafficDataTypes::SAT, "Single alternative line traffic" },
   { TrafficDataTypes::SCI, "Civil emergency" },
   { TrafficDataTypes::SCN, "Service withdrawn" },
   { TrafficDataTypes::SEW, "Sewer overflow" },
   { TrafficDataTypes::SEX, "Civil emergency cancelled" },
   { TrafficDataTypes::SFB, "Service(s) fully blocked" },
   { TrafficDataTypes::SFC, "Service area, fuel station closed" },
   { TrafficDataTypes::SFH, "Heavy snowfall" },
   { TrafficDataTypes::SFL, "Snowfall" },
   { TrafficDataTypes::SFO, "Fuel station reopened" },
   { TrafficDataTypes::SHL, "Shed load(s)" },
   { TrafficDataTypes::SHX, "Skid hazard reduced" },
   { TrafficDataTypes::SLT, "Sleet" },
   { TrafficDataTypes::SLU, "Slush" },
   { TrafficDataTypes::SM, "Snow chains mandatory" },
   { TrafficDataTypes::SMC, "Closed due to smog alert" },
   { TrafficDataTypes::SMG, "Smog alert" },
   { TrafficDataTypes::SMO, "Smoke hazard" },
   { TrafficDataTypes::SMV, "Spillage occurring from moving vehicle" },
   { TrafficDataTypes::SMX, "Smog alert ended" },
   { TrafficDataTypes::SN, "Snowploughs in use" },
   { TrafficDataTypes::SND, "Deep snow" },
   { TrafficDataTypes::SNF, "Fresh snow" },
   { TrafficDataTypes::SNP, "Packed snow" },
   { TrafficDataTypes::SNR, "Snow drifts" },
   { TrafficDataTypes::SNS, "Service not operating, substitute service available" },
   { TrafficDataTypes::SNW, "Lane control signs not working" },
   { TrafficDataTypes::SNX, "Snow cleared" },
   { TrafficDataTypes::SPC, "Police checkpoint" },
   { TrafficDataTypes::SPL, "Spillage on the road" },
   { TrafficDataTypes::SPY, "Spray hazard" },
   { TrafficDataTypes::SR, "Snow chains recommended" },
   { TrafficDataTypes::SRC, "Service area, restaurant closed" },
   { TrafficDataTypes::SRO, "Snow on the road" },
   { TrafficDataTypes::SRX, "Restaurant reopened" },
   { TrafficDataTypes::SSF, "Free shuttle service operating" },
   { TrafficDataTypes::SSM, "Severe smog" },
   { TrafficDataTypes::SSO, "Shuttle service operating" },
   { TrafficDataTypes::STD, "Storm damage" },
   { TrafficDataTypes::STF, "Stud tyres are not authorised" },
   { TrafficDataTypes::STI, "Terrorist incident" },
   { TrafficDataTypes::STM, "Storm force winds" },
   { TrafficDataTypes::STU, "Stud tyres may be used" },
   { TrafficDataTypes::SUB, "Subsidence" },
   { TrafficDataTypes::SVH, "Slow vehicle(s)" },
   { TrafficDataTypes::SWA, "Swarms of insects" },
   { TrafficDataTypes::SWC, "Sewer collapse" },
   { TrafficDataTypes::SWH, "Surface water hazard" },
   { TrafficDataTypes::SWI, "Lane control signs working incorrectly" },
   { TrafficDataTypes::SWN, "Lane control signs operating" },
   { TrafficDataTypes::SWS, "Showers" },
   { TrafficDataTypes::SWT, "Switch your car radio to XX" },
   { TrafficDataTypes::TAL, "Temporary axle load limit" },
   { TrafficDataTypes::TAX, "Temporary axle weight limit lifted" },
   { TrafficDataTypes::TBU, "Traffic building up" },
   { TrafficDataTypes::TCC, "Traffic signal control computer not working" },
   { TrafficDataTypes::TCN, "Traffic congestion" },
   { TrafficDataTypes::TCX, "Traffic problem congestion cleared" },
   { TrafficDataTypes::TDX, "Traffic disruption cleared" },
   { TrafficDataTypes::TEA, "Traffic easing" },
   { TrafficDataTypes::TEX, "Extreme heat" },
   { TrafficDataTypes::TFA, "Temperature falling" },
   { TrafficDataTypes::TGL, "Temporary weight limit lifted" },
   { TrafficDataTypes::TGW, "Temporary gross weight limit" },
   { TrafficDataTypes::THU, "Thunderstorms" },
   { TrafficDataTypes::TIA, "National traffic" },
   { TrafficDataTypes::TIR, "Only major road information provided by this service" },
   { TrafficDataTypes::TLI, "Traffic lights working incorrectly" },
   { TrafficDataTypes::TLN, "Traffic lighter than normal" },
   { TrafficDataTypes::TLO, "Traffic lights not working" },
   { TrafficDataTypes::TLT, "Temporary traffic lights" },
   { TrafficDataTypes::TLV, "Track-laying vehicle(s)" },
   { TrafficDataTypes::TLX, "Less extreme temperatures expected" },
   { TrafficDataTypes::TM, "Snow tyres mandatory" },
   { TrafficDataTypes::TMO, "This message is for test purposes only. Please ignore" },
   { TrafficDataTypes::TMP, "Current temperature" },
   { TrafficDataTypes::TNL, "Normal traffic expected" },
   { TrafficDataTypes::TNW, "Temporary traffic lights not working" },
   { TrafficDataTypes::TOR, "Tornadoes" },
   { TrafficDataTypes::TOX, "Restrictions for high-sided vehicles lifted" },
   { TrafficDataTypes::TR, "Snow tyres recommended" },
   { TrafficDataTypes::TRA, "Trade fair" },
   { TrafficDataTypes::TRC, "Traffic regulations have been changed" },
   { TrafficDataTypes::TRT, "Trip time" },
   { TrafficDataTypes::TRX, "Tornado warning ended" },
   { TrafficDataTypes::TSC, "Traffic signal timings changed" },
   { TrafficDataTypes::TSR, "Traffic signals repaired" },
   { TrafficDataTypes::TSX, "No TMC service available" },
   { TrafficDataTypes::TTB, "Through traffic lanes blocked" },
   { TrafficDataTypes::TTL, "Through traffic lanes closed" },
   { TrafficDataTypes::TTM, "Travel time" },
   { TrafficDataTypes::TUB, "Tunnel blocked" },
   { TrafficDataTypes::TUC, "Tunnel closed" },
   { TrafficDataTypes::TVX, "Tunnel ventilation not working" },
   { TrafficDataTypes::TWI, "Temportary traffic lights working incorrectly" },
   { TrafficDataTypes::TXA, "Information restricted to this area" },
   { TrafficDataTypes::TXB, "Active TMC service on this frequency to be resumed" },
   { TrafficDataTypes::TXC, "Extreme cold" },
   { TrafficDataTypes::TXD, "No detailed regional information provided by this service" },
   { TrafficDataTypes::TXL, "Only local information provided by this service" },
   { TrafficDataTypes::TXN, "No new traffic information available" },
   { TrafficDataTypes::TXO, "No cross-border information provided by this service" },
   { TrafficDataTypes::TXP, "No public transport information available" },
   { TrafficDataTypes::TXR, "Only regional information provided by this service" },
   { TrafficDataTypes::TXS, "TMC broadcast on this frequency will stop" },
   { TrafficDataTypes::TXV, "Information about major events is no longer valid" },
   { TrafficDataTypes::TXW, "Previous announcement about this or other TMC services no longer valid" },
   { TrafficDataTypes::TXX, "No detailed local information provided by this service" },
   { TrafficDataTypes::TXY, "Reference to audio programmes no longer valid" },
   { TrafficDataTypes::TXZ, "Reference to other TMC services no longer valid" },
   { TrafficDataTypes::UBA, "Use of bus lane allowed under carpool restriction" },
   { TrafficDataTypes::UBV, "Use of bus lane allowed for all vehicles" },
   { TrafficDataTypes::UCA, "Use of carpool lane allowed for all vehicles" },
   { TrafficDataTypes::UGI, "Urgent information will be given on normal program broadcast" },
   { TrafficDataTypes::UHA, "Use of hard shoulder allowed" },
   { TrafficDataTypes::UHV, "Use of heavy vehicle lane allowed for all vehicles" },
   { TrafficDataTypes::USI, "Underground services irregular" },
   { TrafficDataTypes::USN, "Underground service not operating" },
   { TrafficDataTypes::VFR, "Vehicle fire(s)" },
   { TrafficDataTypes::VIR, "Visibility reduced" },
   { TrafficDataTypes::VNW, "Variable message signs not working" },
   { TrafficDataTypes::VOD, "Vehicle with overheight load, danger" },
   { TrafficDataTypes::VSA, "Vehicles slowing to look at accident(s)" },
   { TrafficDataTypes::VSM, "Dangerous slow moving vehicle in the roadway" },
   { TrafficDataTypes::VSX, "Visibility improved" },
   { TrafficDataTypes::VWC, "Vehicle(s) on wrong carriageway" },
   { TrafficDataTypes::VWI, "Variable message signs working incorrectly" },
   { TrafficDataTypes::VWN, "Variable message signs operating" },
   { TrafficDataTypes::VWX, "Dangerous vehicle warning cleared" },
   { TrafficDataTypes::WBC, "Work on buried cables" },
   { TrafficDataTypes::WBS, "Work on buried services" },
   { TrafficDataTypes::WHI, "White out" },
   { TrafficDataTypes::WIC, "Crosswinds" },
   { TrafficDataTypes::WIG, "Gusty winds" },
   { TrafficDataTypes::WIS, "Strong winds" },
   { TrafficDataTypes::WIX, "Strong wind have eased" },
   { TrafficDataTypes::WLD, "Wide load(s)" },
   { TrafficDataTypes::WLL, "Temporary width limit lifted" },
   { TrafficDataTypes::WLT, "Temporary width limit" },
   { TrafficDataTypes::WMW, "Water main work" },
   { TrafficDataTypes::WR, "Winter equipment recommended" },
   { TrafficDataTypes::WRM, "Winter equipment mandatory" },
   { TrafficDataTypes::WST, "Winter storm" },
   { TrafficDataTypes::WSX, "Weather situation improved" },
   { TrafficDataTypes::WSZ, "Weather expected to improve" },
   { TrafficDataTypes::EFX, "Unknown(EFX)" },
   { TrafficDataTypes::CAS, "Unknown(CAS)" },
   { TrafficDataTypes::LPR, "Unknown(LPR)" },
   { TrafficDataTypes::WBW, "Unknown(WBW)" },
   { TrafficDataTypes::OtherPhrase, "Other Phrase" },
   { TrafficDataTypes::NoPhrase, "No phrase" }
};

const char* TrafficDataTypes::
getPhraseText( TrafficDataTypes::phrase phrase ) {
   if ( phrase > 522 ) {
      mc2dbg << phrase << endl;
   }
   MC2_ASSERT( phrase <= 522 );

   for ( uint32 i = 0;
         i < sizeof ( phraseArray ) / sizeof ( phraseArray[ 0 ] );
         ++i ) {
      if ( phraseArray[ i ].m_value == phrase ) {
         return phraseArray[ i ].m_text;
      }
   }

   return "";
}
