#
# Copyright (c) 1999 - 2010, Vodafone Group Services Ltd
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#     * Neither the name of the Vodafone Group Services Ltd nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# Some variables
HTMLDIR           = html
#LATEX_PARMS       = -interaction=nonstopmode

# Make sure that the "all" rule is the default-one
default:      all

# The rule to create a .dvi-file from a .tex-file
%.dvi:   %.tex; pushd ../Figures; $(MAKE); popd; \
               export TEXINPUTS="../Figures:../Misc/:"; \
               ../Misc/llatex.zsh ${LATEX_PARMS} '$@' '$<'|| rm -f '$@'

# The rule to create a .ps-file from a .dvi-file
%.ps:   %.dvi; export TEXINPUTS="../Figures:"; \
               dvips -o '$@' '$<'

# The rule to create a .pdf-file from a .ps-file
%.pdf:   %.ps; ps2pdf '$<' '$@'

# Build the html (the Makefile in the subdirectory must set the 
# DOCUMENTNAME-variable.
HTMLTITLE ?= $(DOCUMENTNAME)
html:          $(DOCUMENTNAME).dvi ; \
               export TEXINPUTS="../../Figures:../../Misc/:"; \
               rm -rf $(HTMLDIR); \
               latex2html  -split 4 \
                           -link 1 \
                           -toc_depth 8 \
                           -mkdir \
                           -dir $(HTMLDIR) \
                           -image_type gif \
                           -antialias \
                           -show_section_numbers \
                           -auto_navigation \
                           -index_in_navigation \
                           -nocontents_in_navigation \
                           -next_page_in_navigation \
                           -previous_page_in_navigation \
                           -local_icons \
                           -transparent \
                           -title \"$(HTMLTITLE)\" \
                           -html_version 4.0,table,math \
                           $(DOCUMENTNAME).tex;

# Build a separate dir for html for a document.
%.www: %.tex %.dvi
	export TEXINPUTS="../../Figures:../../Misc/:"; \
               rm -rf $(HTMLDIR); \
               latex2html  -split 4 \
                           -link 1 \
                           -toc_depth 8 \
                           -mkdir \
                           -dir $@ \
                           -image_type gif \
                           -antialias \
                           -show_section_numbers \
                           -auto_navigation \
                           -index_in_navigation \
                           -nocontents_in_navigation \
                           -next_page_in_navigation \
                           -previous_page_in_navigation \
                           -local_icons \
                           -transparent \
                           -title \"$@\" \
                           -html_version 4.0,table,math \
                           $< ;

# Remove all the created files, including the html-directory
clean:         ; rm -f *.eps *.dvi *.log *.toc *.ps *.pdf *.bak *.aux *.idx *.ilg *.ind *.tex~ *.blg *.bbl ; \
               rm -rf $(HTMLDIR)

