from waftools import mc2test

def unit_test( bld, target, source ):
   # The test source file, with main in it
   sources = [ source ]
   # add all files in ../src/ except TrafficServer.cpp
   sources.extend( mc2test.create_sources( bld, '../src/', '*.cpp',
                                          'TrafficServer.cpp' ) )
   test = mc2test.unit_test( bld, target, sources,
                     'ServersServers ServersShared ServersSharedNet \
    ServersSharedDrawing ServersSharedGfx ServersSharedXML \
ServersSharedCommon ServersSharedItems ServersSharedDatabase SharedNet \
Shared',
                     'SHARED SERVER SERVERSSHARED')
   test.defines = 'USE_SSL USE_XML'


def build(bld):
   unit_test( bld, 'TrafficHandlerTest', 'TrafficHandlerTest.cpp' )


