def configure(conf):
    conf.check_cfg( package='openssl', args='--cflags --libs' )


def build(bld):
    staticlib = bld.new_task_gen( 'cxx', 'staticlib' )
    staticlib.source = bld.glob("*.cpp")
    staticlib.includes = '../include ../../include'
    staticlib.target = 'SharedNet'
    staticlib.uselib_local='SharedFileSystem SharedUtility'
    staticlib.uselib = 'OPENSSL'
    staticlib.install_path = None
    staticlib.export_incdirs='../include'
